spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/signature_db
    username: postgres
    password: *******

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: *************
    password: *************

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: mySuperSecretJwtKeyForSignatureApp123456

file:
  upload-dir: D:\projects\pdfsignature\pdfsignature\uploads

signature:
  upload-dir: D:\projects\pdfsignature\pdfsignature\signatures

signed:
  output-dir: D:\projects\pdfsignature\pdfsignature\signed

logging:
  level:
    org.springframework.security: DEBUG